version: '3.4'

services:
  tcc-sigo-normas-api:
    image: tcc-sigo-normas-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 80:80
      - 443:443