name: Docker CI with Git Actions

on: [push]

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  build:
    # Ensure test job passes before pushing image.
    needs: test
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login - Azure Container Registry
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
    
      - name: Build Images
        working-directory: ./20_RestWithASPNETUdemy_DeployToAzure/RestWithASPNETUdemy
        run: docker-compose build
      
      - name: Push to Azure Container registry
        run: |
          docker tag ${{ secrets.IMAGE_NAME }}:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{github.run_id}}
          docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{github.run_id}}
      
      - name: Login in Azure to Deployment
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure WebApp Container - Application Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: tcc-sigo-normas-api
          images:  ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{github.run_id}}
